stages:
  - build
  - test

build:
  image: node:latest
  tags:
    - docker-runner
  stage: build
#  when: manual
  script:
    - yarn
    - yarn run build
    - echo "@vimworldinc:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - yarn publish
    - echo "publish successfully"
  only:
    refs:
      - main
    changes:
      - package.json

include:
  - template: Security/SAST.gitlab-ci.yml
